### ISSUE TITLE
Just a thought on network construction methods

### ISSUE THREAD

**Issue by CodLiver** [anvaka/sayit#1]
First of all, I loved your visualization, ideas etc.

However, I tested your alg. with smaller subs and I got some unrelated answers. I got that you use the method called (people who posted, also posted that) which is fair.

Would you think using subreddit mentions as form of edges can be much accurate?

If you are browsing subreddit A. and that is a small one, but its "relateds" can be subs that are mentioned there. (like citation graphs.)

check r/babysteps for example. thats a manga sub, but the relateds are completely irrelevant, although it could have been r/anime,/manga.

I recommend you to read this https://en.wikipedia.org/wiki/Citation_graph. can be useful. In terms of this wiki, its like building a network of publications where people who published this also published that. can logical, but may not be related.

still I love the idea. :)

**Comment by anvaka** [comment]
Thank you! I actually used subreddit mentions for the popular subreddits where I couldn't find any related subreddits in their `/about` info. They need to be used with caution, as one person (or a bot) can skew the results by pointing to their own subreddits.

Still, definitely could be beneficial to use mentions - I'm going to publish my data collection scripts soon. If someone wants to incorporate citations - I'd be more than happy to accept a PR (assuming they improve recommendations).

**Comment by anvaka** [comment]
Thank you!
