### ISSUE TITLE
How can i fixed

### ISSUE THREAD

**Issue by m35-code** [anvaka/sayit#10]
i need help please
![error](https://user-images.githubusercontent.com/57444809/69034804-587bf900-09e2-11ea-9d69-aa2692d363f8.png)

**Comment by anvaka** [comment]
Interesting. Remove package-lock.json from the project and the run 

```
npm install
```

Does it work?

**Comment by m35-code** [comment]
thanks anvaka ....  but it Does not work

**Comment by anvaka** [comment]
Please provide more information - what did you do, what happened and what do you expect to see?
